language: d

d:
  - dmd-2.069.0
  - dmd-2.068.2
  - dmd-2.067.1

addons:
  apt:
    packages:
    - libev-dev

env:
  - VIBED_DRIVER=libevent
  - VIBED_DRIVER=libev
  - VIBED_DRIVER=libasync_botan

script: ./travis-ci.sh

services:
  - mongodb
  - redis-server

sudo: false
